{{- if .Values.botRunner.enabled }}
# Bot Runner Master
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "the0.fullname" . }}-bot-runner-master
  labels:
    {{- include "the0.labels" . | nindent 4 }}
    app.kubernetes.io/component: bot-runner-master
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.botRunner.master.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.botRunner.master.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "the0.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: bot-runner-master

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "the0.fullname" . }}-bot-runner-master
  labels:
    {{- include "the0.labels" . | nindent 4 }}
    app.kubernetes.io/component: bot-runner-master
spec:
  replicas: {{ .Values.botRunner.master.replicas }}
  selector:
    matchLabels:
      {{- include "the0.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: bot-runner-master
  template:
    metadata:
      labels:
        {{- include "the0.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: bot-runner-master
    spec:
      containers:
        - name: bot-runner-master
          image: {{ .Values.botRunner.image.repository }}:{{ .Values.botRunner.image.tag }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          command: ["./runtime", "bot-runner", "master"]
          ports:
            - name: http
              containerPort: {{ .Values.botRunner.master.port }}
              protocol: TCP
            - name: grpc
              containerPort: {{ .Values.botRunner.master.grpcPort }}
              protocol: TCP
          env:
            {{- range $key, $value := .Values.botRunner.master.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.botRunner.master.resources | nindent 12 }}

# Bot Runner Workers
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "the0.fullname" . }}-bot-runner-worker
  labels:
    {{- include "the0.labels" . | nindent 4 }}
    app.kubernetes.io/component: bot-runner-worker
spec:
  replicas: {{ .Values.botRunner.worker.replicas }}
  selector:
    matchLabels:
      {{- include "the0.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: bot-runner-worker
  template:
    metadata:
      labels:
        {{- include "the0.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: bot-runner-worker
    spec:
      containers:
        - name: bot-runner-worker
          image: {{ .Values.botRunner.image.repository }}:{{ .Values.botRunner.image.tag }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          command: ["./runtime", "bot-runner", "worker"]
          env:
            {{- range $key, $value := .Values.botRunner.worker.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          
          securityContext:
            privileged: {{ .Values.botRunner.worker.privileged }}
            
          volumeMounts:
            {{- range .Values.botRunner.worker.volumes }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
          
          resources:
            {{- toYaml .Values.botRunner.worker.resources | nindent 12 }}
      
      volumes:
        {{- range .Values.botRunner.worker.volumes }}
        - name: {{ .name }}
          hostPath:
            path: {{ .hostPath }}
        {{- end }}
{{- end }}