{{- if not .Values.global.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "the0.fullname" . }}-secrets
  labels:
    {{- include "the0.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgresql-password: {{ .Values.postgresql.password | default "changeme" | quote }}
  mongodb-root-password: {{ .Values.mongodb.rootPassword | default "changeme" | quote }}
  minio-access-key: {{ include "the0.minioAccessKey" . | trim | quote }}
  minio-secret-key: {{ include "the0.minioSecretKey" . | trim | quote }}
  database-url: {{ include "the0.databaseUrl" . | trim | quote }}
  mongo-url: {{ include "the0.mongoUrl" . | trim | quote }}
  jwt-secret: {{ .Values.the0Api.env.JWT_SECRET | default "changeme" | quote }}
{{- end }}
